package io.github._4drian3d.unsignedvelocity.listener;

import com.velocitypowered.proxy.connection.client.ConnectedPlayer;

public interface EventListener {
    void register();
    boolean canBeLoaded();

    default boolean checkConnection(final ConnectedPlayer player) {
        try {
            player.ensureAndGetCurrentServer().ensureConnected();
            return true;
        } catch(final IllegalStateException e) {
            // The player is probably on a fake server or
            // some other place generated by another plugin,
            // so handling the packet would be avoided
            return false;
        }
    }
}
